version: "3.8"

services:
  netbox:
    image: lscr.io/linuxserver/netbox:latest
    container_name: netbox
    env_file: 
      - ./env/netbox.env
    volumes:
      - ./data/netbox:/config
    ports:
      - 8000:8000
    depends_on:
      - postgres
      - redis
    networks:
      - netbox_net
    
  postgres:
    image: postgres:12
    container_name: postgres
    env_file:
      - ./env/postgres.env
    volumes:
      - ./data/postgres:/var/lib/postgresql/data
    networks:
      - netbox_net
    
  redis:
    image: redis:6.0
    container_name: redis
    volumes:
      - ./data/redis:/data
      - ./env/redis.conf:/usr/local/etc/redis/redis.conf
    networks:
      - netbox_net
    command: ["redis-server", "/usr/local/etc/redis/redis.conf"]

networks:
  netbox_net:
    driver: bridge
